export const materias = {
  "ADE-101": {
    asignatura: "ADMINISTRACION I",
    creditos: 3,
    semestre: 1,
  },
  "FGC-102": {
    asignatura: "MÉTODO DEL TRABAJO ACADÉMICO",
    creditos: 2,
    semestre: 1,
  },
  "FGC-101": {
    asignatura: "ORIENTACIÓN ACADÉMICA INSTITUCIONAL",
    creditos: 2,
    semestre: 1,
  },
  "FGC-103": {
    asignatura: "METODOLOGÍA DE LA INVESTIGACIÓN",
    creditos: 3,
    semestre: 1,
  },
  "FGC-104": {
    asignatura: "LENGUA ESPAÑOLA I",
    creditos: 3,
    pre: "FGC-102",
    semestre: 2,
  },
  "ING-101": {
    asignatura: "INTRODUCCIÓN A LA INGENIERÍA",
    creditos: 3,
    semestre: 2,
  },
  "FGC-106": {
    asignatura: "TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN I",
    creditos: 3,
    semestre: 2,
  },
  "FGC-105": {
    asignatura: "MATEMÁTICA BÁSICA I",
    creditos: 3,
    pre: "FGC-102",
    semestre: 2,
  },
  "DMF-209": {
    asignatura: "FISICA I",
    creditos: 4,
    pre: "FGC-105",
    semestre: 3,
  },
  "MTI-200": {
    asignatura: "MATEMÁTICA II",
    creditos: 4,
    pre: "FGC-105",
    semestre: 3,
  },
  "FGC-107": {
    asignatura: "HISTORIA SOCIAL DOMINICANA",
    creditos: 3,
    pre: "FGC-102",
    semestre: 3,
  },
  "FGC-108": {
    asignatura: "INGLÉS I",
    creditos: 3,
    pre: "FGC-102",
    semestre: 3,
  },
  "QUI-400": {
    asignatura: "QUÍMICA I",
    creditos: 3,
    pre: "FGC-105",
    semestre: 3,
  },
  "FGC-110": {
    asignatura: "DESARROLLO SOSTENIBLE Y GESTIÓN DE RIESGOS",
    creditos: 2,
    pre: "FGC-102",
    semestre: 4,
  },
  "FGC-109": {
    asignatura: "FILOSOFÍA",
    creditos: 2,
    pre: "FGC-102",
    semestre: 4,
  },
  "MTI-300": {
    asignatura: "MATEMÁTICA III",
    creditos: 4,
    pre: "MTI-200",
    semestre: 4,
  },
  "DMF-210": {
    asignatura: "FISICA II",
    creditos: 4,
    pre: "DMF-209",
    semestre: 4,
  },
  "INF-215": {
    asignatura: "INGENIERÍA ECONÓMICA",
    creditos: 3,
    pre: "MTI-200",
    semestre: 5,
  },
  "MAT-241": {
    asignatura: "ESTADISTICA I",
    creditos: 3,
    pre: "FGC-105",
    semestre: 5,
  },
  "ING-102": {
    asignatura: "CIENCIA E INGENIERÍA DE MATERIALES",
    creditos: 4,
    pre: "QUI-400",
    semestre: 5,
  },
  "ING-103": {
    asignatura: "CÁLCULO INTEGRAL",
    creditos: 4,
    pre: "MTI-300",
    semestre: 5,
  },
  "MAT-242": {
    asignatura: "ESTADISTICA II",
    creditos: 3,
    pre: "MAT-241",
    semestre: 6,
  },
  "INF-222": {
    asignatura: "SISTEMA OPERATIVO I",
    creditos: 3,
    pre: "FGC-106",
    semestre: 6,
  },
  "INF-221": {
    asignatura: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    creditos: 3,
    pre: "FGC-106",
    semestre: 6,
  },
  "ING-105": {
    asignatura: "TALLER DE MECÁNICA DE HARDWARE",
    creditos: 3,
    pre: "FGC-106",
    semestre: 6,
  },
  "ING-104": {
    asignatura: "CÁLCULO VECTORIAL",
    creditos: 4,
    pre: "ING-103",
    semestre: 6,
  },
  "TIC-408": {
    asignatura: "SEGURIDAD DE LA INFORMACIÓN",
    creditos: 3,
    pre: "FGC-106",
    semestre: 7,
  },
  "IND-101": {
    asignatura: "CIENCIA DE LOS DATOS",
    creditos: 3,
    semestre: 7,
  },
  "INF-437": {
    asignatura: "REDES INFORMÁTICAS",
    creditos: 3,
    pre: "FGC-106",
    semestre: 7,
  },
  "ISW-301": {
    asignatura: "TALLER DE PROGRAMACIÓN I",
    creditos: 5,
    pre: "INF-221",
    semestre: 7,
  },
  "ISW-321": {
    asignatura: "TALLER DE BASES DE DATOS I",
    creditos: 4,
    pre: "INF-221",
    semestre: 8,
  },
  "TIC-402": {
    asignatura: "ETICA EN TECNOLOGÍA",
    creditos: 2,
    semestre: 8,
  },
  "IND-404": {
    asignatura: "ELECTIVA I",
    creditos: 3,
    pre: "7MO. CUAT.",
    semestre: 8,
  },
  "IND-314": {
    asignatura: "TEORIA DE LA INFORMACIÓN",
    creditos: 3,
    pre: "IND-101",
    semestre: 8,
  },
  "IND-324": {
    asignatura: "SEÑALES Y SISTEMAS",
    creditos: 3,
    pre: "IND-314",
    semestre: 9,
  },
  "IND-325": {
    asignatura: "BÚSQUEDA Y ANALISIS DE LA INFORMACIÓN",
    creditos: 3,
    pre: "IND-314",
    semestre: 9,
  },
  "IND-334": {
    asignatura: "ESTADÍSTICAS APLICADA A LA CIENCIA DE DATOS",
    creditos: 3,
    pre: "MAT-242",
    semestre: 9,
  },
  "IND-332": {
    asignatura: "HERRAMIENTAS DE ANÁLISIS DE DATOS I",
    creditos: 4,
    pre: "IND-101",
    semestre: 9,
  },
  "IND-335": {
    asignatura: "INGENÍERIA DE DATOS I",
    creditos: 4,
    pre: "IND-314",
    semestre: 9,
  },
  
  "IND-333": {
    asignatura: "TRATAMIENTO DE AUDIO, VIDEO Y VISIÓN ARTIFICIAL",
    creditos: 4,
    pre: "IND-324",
    semestre: 10,
  },
  "IND-412": {
    asignatura: "HERRAMIENTAS DE ANÁLISIS DE DATOS II",
    creditos: 4,
    pre: "IND-332",
    semestre: 10,
  },
  "IND-405": {
    asignatura: "ELECTIVA II",
    creditos: 3,
    pre: "9NO. C.",
    semestre: 10,
  },
  "IND-401": {
    asignatura: "PROYECTO DE DATOS E IO - I",
    creditos: 5,
    pre: "IND-335",
    semestre: 10,
  },
  "IND-403": {
    asignatura: "PASANTÍA - PRÁCTICA DE INGENIERÍA DE DATOS E IO",
    pre: "IND-335",
    semestre: 10,
  },
 
 
  "IND-413": {
    asignatura: "INGENÍERIA DE DATOS II",
    creditos: 4,
    pre: "IND-335",
    semestre: 11,
  },  
  "IND-431": {
    asignatura: "VISUALIZACIÓN DE DATOS",
    creditos: 4,
    pre: "IND-325",
    semestre: 11,
  },
  "IND-402": {
    asignatura: "PROYECTO DE DATOS E IO - II",
    creditos: 5,
    pre: "IND-401",
    semestre: 11,
  },
  "IND-414": {
    asignatura: "INGENIERÍA DE BIG DATA",
    creditos: 4,
    pre: "ISW-321",
    semestre: 11,
  },
  "FGC-111": {
    asignatura: "SEMINARIO DE GRADO",
    creditos: 3,
    pre: "FGC-103",
    semestre: 11,
  },
  "IND-421": {
    asignatura: "APLICACIONES E INFRAESTRUCTURA DE BIG DATA",
    creditos: 4,
    pre: "IND-414",
    semestre: 12,
  },
  "IND-423": {
    asignatura: "MINERÍA DE DATOS",
    creditos: 4,
    pre: "ISW-321",
    semestre: 12,
  },
  "IND-432": {
    asignatura: "INTELIGENCIA DE NEGOCIOS",
    creditos: 3,
    pre: "IND-413",
    semestre: 12,
  },
 
  "IND-600": {
    asignatura: "PROYECTO INTEGRADOR DE DATOS E IO: TRABAJO DE GRADO",
    pre: "FGC-111,IND-402",
    semestre: 12,
  },
};
